### ISSUE TITLE
行情价格多出小数部分

### ISSUE THREAD

**Issue by qinglok** [nicai0609/JAVA-CTPAPI#10]
某些合约如ru2305，买1卖1最新价，会多出小数部分。
之后使用c++的行情工具去验证发现并无此情况。
`
instrumentid,last_price,bid_price1,ask_price1

ru2305,12910.000000000002,12910.000000000002,12915.000000000002
`

**Comment by nicai0609** [comment]
取小数点后3位有效值就行，如：round(pDepthMarketData.LastPrice, 3)
