### ISSUE TITLE
请问能否CTP官方是已经更新到6.3.19了吗，本API是否会同步更新，谢谢了

### ISSUE THREAD

**Issue by omobh** [nicai0609/JAVA-CTPAPI#3]
请问能否CTP官方是已经更新到6.3.19了吗，本API是否会同步更新，谢谢了

**Comment by nicai0609** [comment]
是的，但是现在6.3.15和6.3.19P1是兼容的，6.3.16和6.3.19T1是兼容的。不更新也可以正常使用

**Comment by jaezone** [comment]
你好, 6.3.16版本的API哪里获取?

**Comment by nicai0609** [comment]
已更新到最新的v6.6.1
